name: GitHub Projects Automation

on:
  issues:
    types: [closed]

jobs:
  move-issue-to-done:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Move the closed issue to the "Done" column
      - name: Move issue to Done
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"column_id": "PROJECT_COLUMN_ID", "content_type": "Issue", "content_id": "'${{ github.event.issue.id }}'"}' \
            https://api.github.com/projects/columns/PROJECT_COLUMN_ID/cards
