name: GitHub Projects Automation with README Update

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: echo "Pull Request merged, updating README."

      - name: Update README
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set the token as an env variable.
          ACTOR_USERNAME: ${{ github.actor }} # Set the actor username as an env variable.
          GITHUB_REPOSITORY: ${{ github.repository }} # Set the repository as an env variable.
        run: ./.github/scripts/update_readme.sh
